[package]
name = "Compression"
version = "0.1.0"
edition = "2021"

[dependencies]

priority-queue = "2.1.0"
bincode = "1.3"
config = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
bit-vec = "0.8.0"